import { Contact, Note, BusinessCard, User } from "@/types";

const USER_ID = "user-demo-001";

export const mockUser: User = {
  id: USER_ID,
  email: "demo@fomo.ai",
  full_name: "Demo User",
  demo_mode: true,
  created_at: new Date().toISOString(),
};

export const mockContacts: Contact[] = [
  {
    id: "contact-001",
    user_id: USER_ID,
    full_name: "Alex Rivera",
    company: "AeroTech Solutions",
    email: "alex.rivera@aerotech.com",
    phone: "+1-555-0101",
    linkedin_url: "https://linkedin.com/in/alexrivera",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "contact-002",
    user_id: USER_ID,
    full_name: "Dana Chu",
    company: "SkyLink Ventures",
    email: "dana@skylink.vc",
    phone: "+1-555-0202",
    linkedin_url: "https://linkedin.com/in/danachu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dana",
    created_at: "2025-01-10T14:30:00Z",
    updated_at: "2025-01-10T14:30:00Z",
  },
  {
    id: "contact-003",
    user_id: USER_ID,
    full_name: "Brian Papazian",
    company: "Handyman SD",
    email: "brian@handymansd.com",
    phone: "+1-858-555-0199",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Brian",
    created_at: "2025-01-05T09:15:00Z",
    updated_at: "2025-01-05T09:15:00Z",
  },
];

export const mockNotes: Note[] = [
  {
    id: "note-001",
    user_id: USER_ID,
    contact_id: "contact-001",
    audio_url: "/mock-audio-1.mp3",
    transcript: "Met with Alex at the AeroTech booth during CES. They're launching a new drone platform in Q2 and are looking for partners in the logistics space. Seemed really interested when I mentioned our supply chain software. Alex mentioned they're currently evaluating 3 different providers but haven't made a decision yet. Budget is confirmed at around $250K for the initial rollout.",
    summary: [
      "Met at CES booth to discuss new Q2 drone platform launch",
      "Strong interest in logistics partnership with our supply chain software",
      "Evaluating 3 providers, budget confirmed at ~$250K initial rollout",
    ],
    next_step: "Email detailed pricing sheet and case studies by Friday Jan 24",
    due_date: "2025-01-24T17:00:00Z",
    tags: ["trade show", "partnership", "pricing", "drone-tech"],
    photo_urls: ["/mock-photo-booth.jpg"],
    status: "ready",
    created_at: "2025-01-20T15:30:00Z",
    updated_at: "2025-01-20T15:35:00Z",
  },
  {
    id: "note-002",
    user_id: USER_ID,
    contact_id: "contact-002",
    audio_url: "/mock-audio-2.mp3",
    transcript: "Quick coffee catch-up with Dana from SkyLink. They're interested in potentially leading our Series A round. Dana asked about our current runway, burn rate, and key metrics. I shared that we're at $2M ARR growing 15% MoM with 18 months runway. They want to see our pitch deck and financial projections for the next board meeting.",
    summary: [
      "Coffee meeting about potential Series A investment from SkyLink",
      "Shared key metrics: $2M ARR, 15% MoM growth, 18mo runway",
      "Requested pitch deck and projections for upcoming board meeting",
    ],
    next_step: "Send updated pitch deck and financial model by Tuesday",
    due_date: "2025-01-21T12:00:00Z",
    tags: ["fundraising", "vc", "series-a"],
    status: "ready",
    created_at: "2025-01-18T11:00:00Z",
    updated_at: "2025-01-18T11:05:00Z",
  },
  {
    id: "note-003",
    user_id: USER_ID,
    contact_id: "contact-003",
    audio_url: "/mock-audio-3.mp3",
    status: "processing",
    created_at: "2025-01-20T16:45:00Z",
    updated_at: "2025-01-20T16:45:00Z",
  },
  {
    id: "note-004",
    user_id: USER_ID,
    contact_id: "contact-001",
    transcript: "Follow-up call with Alex about integration requirements. They need API access to real-time flight data and geofencing capabilities. Technical team will be reaching out next week for a deeper dive. Also mentioned they're presenting our solution to their board on Feb 5.",
    summary: [
      "Discussed technical requirements: API access and geofencing needed",
      "Technical team follow-up scheduled for next week",
      "Board presentation scheduled for Feb 5",
    ],
    next_step: "Prepare technical documentation for their engineering team",
    due_date: "2025-01-25T17:00:00Z",
    tags: ["follow-up", "technical", "api", "integration"],
    status: "ready",
    created_at: "2025-01-19T14:20:00Z",
    updated_at: "2025-01-19T14:25:00Z",
  },
  {
    id: "note-005",
    user_id: USER_ID,
    contact_id: "contact-002",
    transcript: "Dana introduced me to their portfolio company CEO who's looking for similar solutions. Great networking opportunity. They're in the same space but focused on international markets which could be complementary.",
    summary: [
      "Introduction to portfolio company CEO with complementary focus",
      "International market opportunity identified",
      "Potential partnership or collaboration discussed",
    ],
    next_step: "Schedule intro call with portfolio company CEO",
    tags: ["networking", "intro", "international"],
    photo_urls: ["/mock-photo-conference.jpg", "/mock-photo-team.jpg"],
    status: "ready",
    created_at: "2025-01-17T10:30:00Z",
    updated_at: "2025-01-17T10:35:00Z",
  },
  {
    id: "note-006",
    user_id: USER_ID,
    contact_id: "contact-003",
    transcript: "Brian showed me their new workshop setup and the CRM system they're currently using. It's pretty basic and they're frustrated with the lack of mobile features. Perfect fit for our solution. He's the decision maker and seemed ready to move fast if the price is right.",
    summary: [
      "Toured new workshop and reviewed current CRM pain points",
      "Frustrated with lack of mobile features - our key differentiator",
      "Brian is decision maker and ready to move quickly on right price",
    ],
    next_step: "Send proposal with mobile-first feature comparison",
    due_date: "2025-01-22T17:00:00Z",
    tags: ["demo", "crm", "mobile", "proposal"],
    status: "ready",
    created_at: "2025-01-16T13:45:00Z",
    updated_at: "2025-01-16T13:50:00Z",
  },
];

export const mockBusinessCards: BusinessCard[] = [
  {
    id: "card-001",
    user_id: USER_ID,
    contact_id: "contact-001",
    image_url: "/mock-card-1.jpg",
    ocr_text: "Alex Rivera\nCEO & Founder\nAeroTech Solutions\nalex.rivera@aerotech.com\n+1-555-0101",
    extracted: {
      name: "Alex Rivera",
      company: "AeroTech Solutions",
      email: "alex.rivera@aerotech.com",
      phone: "+1-555-0101",
    },
    linkedin_guess: "https://linkedin.com/in/alexrivera",
    processed_at: "2025-01-15T10:05:00Z",
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:05:00Z",
  },
  {
    id: "card-002",
    user_id: USER_ID,
    image_url: "/mock-card-2.jpg",
    ocr_text: "Sarah Mitchell\nHead of Partnerships\nQuantum Labs\nsarah.m@quantumlabs.io\n+1-555-0303",
    extracted: {
      name: "Sarah Mitchell",
      company: "Quantum Labs",
      email: "sarah.m@quantumlabs.io",
      phone: "+1-555-0303",
    },
    linkedin_guess: "https://linkedin.com/in/sarahmitchell",
    created_at: "2025-01-19T16:00:00Z",
    updated_at: "2025-01-19T16:00:00Z",
  },
];
