import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Camera, CreditCard } from "lucide-react";
import { RecordButton } from "@/components/RecordButton";
import { ContactPicker } from "@/components/ContactPicker";
import { PhotoGrid } from "@/components/PhotoGrid";
import { LoadingOverlay } from "@/components/LoadingOverlay";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { Contact } from "@/types";

export default function Capture() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [isRecording, setIsRecording] = useState(false);
  const [audioUrl, setAudioUrl] = useState<string>();
  const [selectedContactId, setSelectedContactId] = useState<string | null>(null);
  const [photos, setPhotos] = useState<string[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);

  const { data: contacts = [] } = useQuery({
    queryKey: ["contacts", user?.id],
    queryFn: async () => {
      if (!user) return [];
      const { data, error } = await supabase
        .from("contacts")
        .select("*")
        .eq("user_id", user.id)
        .order("full_name");
      
      if (error) throw error;
      return data as Contact[];
    },
    enabled: !!user,
  });

  const handleStartRecording = () => {
    setIsRecording(true);
  };

  const handleStopRecording = async (duration: number) => {
    setIsRecording(false);
    // Mock audio URL for now - in production this would upload to storage
    const mockAudioUrl = `/mock-audio-${Date.now()}.mp3`;
    setAudioUrl(mockAudioUrl);
    toast.success("Recording saved!");
  };

  const handleAddPhotos = async () => {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = "image/*";
    input.multiple = true;
    input.onchange = async (e) => {
      const files = Array.from((e.target as HTMLInputElement).files || []);
      if (files.length > 0) {
        // Mock photo URLs for now - in production this would upload to storage
        const mockUrls = files.map((_, i) => `/mock-photo-${Date.now()}-${i}.jpg`);
        setPhotos([...photos, ...mockUrls]);
        toast.success(`Added ${files.length} photo(s)`);
      }
    };
    input.click();
  };

  const handleScanCard = () => {
    navigate("/scan-card");
  };

  const handleCreateContact = () => {
    navigate("/contacts/new");
  };

  const handleSaveNote = async () => {
    if (!audioUrl) {
      toast.error("Please record audio first");
      return;
    }

    if (!user) {
      toast.error("You must be logged in");
      return;
    }

    setIsProcessing(true);
    try {
      // Create note in database
      const { data: note, error } = await supabase
        .from("notes")
        .insert({
          user_id: user.id,
          contact_id: selectedContactId,
          audio_url: audioUrl,
          photo_urls: photos,
          status: "processing",
          transcript: "Processing...",
          summary: ["Processing audio..."],
        })
        .select()
        .single();

      if (error) throw error;

      // Simulate AI processing (in production, this would call an edge function)
      setTimeout(async () => {
        const { error: updateError } = await supabase
          .from("notes")
          .update({
            status: "ready",
            transcript: "This is a simulated transcript of your recording. In production, this would be generated by AI.",
            summary: [
              "Discussed key topics from the conversation",
              "Identified action items and next steps",
              "Noted important details for follow-up"
            ],
            next_step: "Follow up within 2 days",
            tags: ["meeting", "follow-up"],
          })
          .eq("id", note.id);

        if (updateError) throw updateError;

        toast.success("Note saved successfully!");
        navigate(`/note/${note.id}`);
      }, 2000);
    } catch (error: any) {
      toast.error(error.message || "Failed to save note");
      setIsProcessing(false);
    }
  };

  const canSave = audioUrl && !isRecording;

  return (
    <div className="min-h-screen pb-24">
      {isProcessing && <LoadingOverlay message="Processing your note..." />}
      
      <div className="max-w-2xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-12">
          <img 
            src={new URL('@/assets/heyluca-logo.png', import.meta.url).href} 
            alt="HeyLuca" 
            className="h-10 mx-auto mb-4"
          />
          <p className="text-text-muted">Record a 60-second follow-up memory</p>
        </div>

        {/* Record Button */}
        <div className="mb-12 flex justify-center">
          <RecordButton
            onStart={handleStartRecording}
            onStop={handleStopRecording}
          />
        </div>

        {/* Form */}
        <div className="space-y-6">
          {/* Contact Picker */}
          <div>
            <label className="block text-sm font-medium text-text mb-2">
              Contact
            </label>
            <ContactPicker
              contacts={contacts}
              selectedId={selectedContactId}
              onSelect={setSelectedContactId}
              onCreateNew={handleCreateContact}
            />
          </div>

          {/* Action Buttons */}
          <div className="grid grid-cols-2 gap-3">
            <Button
              variant="outline"
              onClick={handleAddPhotos}
              className="gap-2"
            >
              <Camera className="w-4 h-4" />
              Add Photos
            </Button>
            <Button
              variant="outline"
              onClick={handleScanCard}
              className="gap-2"
            >
              <CreditCard className="w-4 h-4" />
              Scan Card
            </Button>
          </div>

          {/* Photos */}
          {photos.length > 0 && (
            <div>
              <label className="block text-sm font-medium text-text mb-2">
                Photos ({photos.length})
              </label>
              <PhotoGrid
                urls={photos}
                onRemove={(index) => setPhotos(photos.filter((_, i) => i !== index))}
              />
            </div>
          )}

          {/* Save Button */}
          <Button
            size="lg"
            onClick={handleSaveNote}
            disabled={!canSave}
            className="w-full"
          >
            Save Note
          </Button>

          {!audioUrl && (
            <p className="text-sm text-text-muted text-center">
              Record audio to enable saving
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
